### ISSUE TITLE
Menu highlighting incorrect

### ISSUE THREAD

**Issue by alfraser86** [wellcometrust/upd#59]
The menu on the left of the case study section highlights as you scroll down, but the linking is wrong and a section only highlights when you're passed it. – not clear about this one. Action, Jen please clarify what browser and on what device you are seeing this please

**Comment by alfraser86** [comment]
@timswalling I think this is one for you. I just need to clarify exactly what is expected.

**Comment by timswalling** [comment]
I'll check the links used in the in the pattern library, but that shouldn't affect the live site - it's an issue with the mocked data, not functionality.

I've noticed that there is an issue caused by the fixed-position nav bar: the item is only highlighted once the heading reaches the top of the viewport, not the bottom of the nav bar. I'll fix this now, as this will have an impact on the live site.

**Comment by alfraser86** [comment]
Think this is now fine
